language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.8
            - g++-5
            - gcc-5

matrix:
  include:
    - os: linux
      compiler: gcc-5

    - os: linux
      compiler: clang-3.7

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential m4 libgmp3-dev cmake

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++" CC="clang"; fi
  - cd StormLib
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - cd bncsutil/src/bncsutil
  - make
  - sudo make install
  - cd ../../..

script:
  - make
  - sudo make install

notifications-policy: &notifications-policy
  on_success: change
  on_failure: always

notifications:
  email: false
  irc:
    channels:
      - "irc.quakenet.org#clan007"
    <<: *notifications-policy

