language: cpp
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc-5
      env: COMPILER=g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5

    - os: linux
      compiler: clang-3.6
      env: COMPILER=clang++
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-3.6
            - llvm-3.6-dev # for LLVMGold.so

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential m4 libgmp3-dev cmake

install:
  - if [ "$COMPILER" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$COMPILER" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - cd StormLib
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - cd bncsutil/src/bncsutil
  - make
  - sudo make install
  - cd ../../..

script:
  - make
  - sudo make install

notifications-policy: &notifications-policy
  on_success: change
  on_failure: always

notifications:
  email: false
  irc:
    channels:
      - "irc.quakenet.org#clan007"
    <<: *notifications-policy

