language: cpp

compiler:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
  # g++ 5
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang 3.7
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main' >> /etc/apt/sources.list"; fi
  - if [ "$CXX" == "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -; fi
  - sudo apt-get update -qq
  - sudo apt-get install build-essential m4 libgmp3-dev cmake

install:
  # g++ 5
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; CC="gcc-5"; fi

  # clang 3.7
  - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq update; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq binutils-gold clang-3.7; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; CC="clang-3.7"; fi
  - if [ "$CXX" == "clang++" ]; then export LD_LIBRARY_PATH="/usr/lib/llvm-${LLVM_VERSION}/lib/"; fi
  - if [ "$CXX" == "clang++" ]; then export PATH="/usr/lib/llvm-${LLVM_VERSION}/bin:$PATH"; fi

  - cd StormLib
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - cd bncsutil/src/bncsutil
  - make
  - sudo make install
  - cd ../../..

script:
  - make
  - sudo make install

notifications-policy: &notifications-policy
  on_success: change
  on_failure: always

notifications:
  email: false
  irc:
    channels:
      - "irc.quakenet.org#clan007"
    <<: *notifications-policy

